spark.master                     spark://master:7077
spark.eventLog.enabled           false
spark.history.fs.logDirectory    file:///opt/bigdata/logs/spark-history
spark.hadoop.fs.defaultFS        hdfs://master:9000
