#!/usr/bin/env bash
export JAVA_HOME=/opt/java/openjdk
export SPARK_MASTER_HOST=master
export SPARK_MASTER_PORT=7077
export SPARK_MASTER_WEBUI_PORT=8080
export SPARK_WORKER_CORES=2
export SPARK_WORKER_MEMORY=1g
export SPARK_WORKER_DIR=/opt/bigdata/data/spark-work
export SPARK_LOG_DIR=/opt/bigdata/logs/spark
export HADOOP_CONF_DIR=/opt/bigdata/conf/hadoop
